# Generated by Django 4.2 on 2023-09-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_film_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='film',
            name='release',
        ),
        migrations.RemoveField(
            model_name='film',
            name='seo',
        ),
        migrations.RemoveField(
            model_name='film',
            name='trailer_url',
        ),
        migrations.RemoveField(
            model_name='film',
            name='type_2D',
        ),
        migrations.RemoveField(
            model_name='film',
            name='type_3D',
        ),
        migrations.RemoveField(
            model_name='film',
            name='type_IMAX',
        ),
    ]
