# Generated by Django 4.2 on 2023-09-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_remove_film_gallery_remove_film_release_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='trailer_url',
            field=models.URLField(blank=True),
        ),
    ]
