# Generated by Django 4.2 on 2023-09-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_seo', '0002_image_image_alter_image_gallery'),
        ('cinema', '0006_film_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='gallery',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='gallery_seo.imagegallery'),
            preserve_default=False,
        ),
    ]
