# Generated by Django 4.2 on 2023-09-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='media/img/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gallery_seo.imagegallery'),
        ),
    ]
